"""Deterministic organization attribution for normalized Hunter records."""

from .asn_organization import (
    CAIDA_AS2ORG_ADAPTER,
    CAIDA_AS2ORG_NAMESPACE,
    CAIDA_AS2ORG_SOURCE_ID,
    AsnOrganizationAuthority,
    AsnOrganizationEnrichmentConflict,
    AsnOrganizationRecord,
    adapt_caida_as2org,
    load_caida_as2org_authority,
    load_caida_as2org_authority_from_text,
    parse_as2org_text,
)
from .authority_sources import (
    CHINA_INSTITUTION_RANGE_ADAPTER,
    CISA_DOTGOV_SOURCE_ID,
    DOMAIN_ORG_ASSOCIATION_ADAPTER,
    EXACT_IP_ORG_ASSOCIATION_ADAPTER,
    GOV_DOMAIN_REGISTRY_ADAPTER,
    ROR_DOMAIN_AUTHORITY_ADAPTER,
    ROR_NAMESPACE,
    adapt_china_institution_ranges,
    adapt_cisa_dotgov,
    adapt_domain_org,
    adapt_exact_ip_org,
    adapt_ror_domains,
    load_china_institution_range_authority,
    load_cisa_dotgov_authority,
    load_domain_org_authority,
    load_exact_ip_org_authority,
    load_ror_domain_authority,
    ror_identifier,
)
from .composition import AuthorityArtifact, AuthorityComposition, compose_engine
from .crosswalk import (
    ALIAS_CROSSWALK_CONFLICT,
    AliasCrosswalk,
    CONSTRUCTION_RULE,
    CrosswalkAlias,
    build_alias_crosswalk_from_authorities,
)
from .engine import AttributionEngine
from .hunter_adapter import normalize_hunter_record
from .models import AttributionResult, NormalizedHunterRecord
from .production_adapter import Measurement212Projection, project_measurement212_hunter_record
from .provenance import AuthoritySourceError, AuthoritySpec, load_authority, load_authority_rows
from .public_suffix import (
    PSL_ICANN_SECTION,
    PSL_PRIVATE_SECTION,
    PSL_SOURCE_URL,
    PslRule,
    PublicSuffixList,
)

__all__ = [
    "ALIAS_CROSSWALK_CONFLICT",
    "AliasCrosswalk",
    "AttributionEngine",
    "AttributionResult",
    "AuthorityArtifact",
    "AuthorityComposition",
    "AuthoritySourceError",
    "AuthoritySpec",
    "AsnOrganizationAuthority",
    "AsnOrganizationEnrichmentConflict",
    "AsnOrganizationRecord",
    "CAIDA_AS2ORG_ADAPTER",
    "CAIDA_AS2ORG_NAMESPACE",
    "CAIDA_AS2ORG_SOURCE_ID",
    "CHINA_INSTITUTION_RANGE_ADAPTER",
    "CISA_DOTGOV_SOURCE_ID",
    "CONSTRUCTION_RULE",
    "CrosswalkAlias",
    "DOMAIN_ORG_ASSOCIATION_ADAPTER",
    "EXACT_IP_ORG_ASSOCIATION_ADAPTER",
    "GOV_DOMAIN_REGISTRY_ADAPTER",
    "Measurement212Projection",
    "NormalizedHunterRecord",
    "PSL_ICANN_SECTION",
    "PSL_PRIVATE_SECTION",
    "PSL_SOURCE_URL",
    "PslRule",
    "PublicSuffixList",
    "ROR_DOMAIN_AUTHORITY_ADAPTER",
    "ROR_NAMESPACE",
    "adapt_caida_as2org",
    "adapt_china_institution_ranges",
    "adapt_cisa_dotgov",
    "adapt_domain_org",
    "adapt_exact_ip_org",
    "adapt_ror_domains",
    "build_alias_crosswalk_from_authorities",
    "compose_engine",
    "load_authority",
    "load_authority_rows",
    "load_caida_as2org_authority",
    "load_caida_as2org_authority_from_text",
    "load_china_institution_range_authority",
    "load_cisa_dotgov_authority",
    "load_domain_org_authority",
    "load_exact_ip_org_authority",
    "load_ror_domain_authority",
    "normalize_hunter_record",
    "parse_as2org_text",
    "project_measurement212_hunter_record",
    "ror_identifier",
]
